name: notification_badge
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.11.5
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^26.3.4

flutter:
  plugin:
    platforms:
      android:
        package: com.gtirkha.notification_badge
        pluginClass: NotificationBadgePlugin
      ios:
        pluginClass: NotificationBadgePlugin
