// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.gtirkha.notification_badge.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object NotificationBadgeApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()
private open class NotificationBadgeApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}


/**
 * API for managing app icon badge counts on Android and iOS.
 *
 * On iOS, badges are set directly via `UNUserNotificationCenter`.
 * On Android, manufacturer-specific providers are tried first; if none
 * succeed, a silent notification-based fallback is used (configurable via
 * [setAndroidNotificationConfig]).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface NotificationBadgeApi {
  /** Returns `true` if at least one badge provider is available on this device. */
  fun isSupported(callback: (Result<Boolean>) -> Unit)
  /** Sets the app icon badge to [count]. Returns `true` on success. */
  fun setCount(count: Long, callback: (Result<Boolean>) -> Unit)
  /** Returns the current badge count stored by the plugin. */
  fun getBadgeCount(callback: (Result<Long>) -> Unit)
  /** Clears the badge by setting the count to 0. Returns `true` on success. */
  fun clearBadge(callback: (Result<Boolean>) -> Unit)
  /** Returns the device manufacturer string (e.g. `"samsung"`, `"Apple"`). */
  fun getDeviceManufacturer(callback: (Result<String>) -> Unit)
  /** Increments the badge count by 1. Returns `true` on success. */
  fun incrementCount(callback: (Result<Boolean>) -> Unit)
  /** Decrements the badge count by 1 (minimum 0). Returns `true` on success. */
  fun decrementCount(callback: (Result<Boolean>) -> Unit)
  /** Returns `true` if the app has permission to display badge notifications. */
  fun checkPermissions(callback: (Result<Boolean>) -> Unit)
  /**
   * Requests permission to display badge notifications.
   *
   * Returns `true` if permission was granted. On Android below API 33,
   * always returns `true`. On iOS, shows the system permission dialog.
   */
  fun requestPermissions(callback: (Result<Boolean>) -> Unit)
  /**
   * Configures the notification used by the Android universal badge fallback.
   *
   * This is only relevant on Android. The universal fallback posts a silent,
   * low-priority notification to display a badge count on devices where no
   * manufacturer-specific badge API is available.
   *
   * - [notificationIcon]: drawable resource name in your app (default `ic_notification`).
   * - [notificationTitle]: title shown in the notification shade. `null` renders a blank title.
   * - [notificationMessage]: body text shown in the notification shade. `null` renders a blank body.
   * - [fallbackToUniversaLAndroidBadger]: set to `false` to disable the fallback entirely.
   */
  fun setAndroidNotificationConfig(notificationIcon: String, notificationTitle: String?, notificationMessage: String?, fallbackToUniversaLAndroidBadger: Boolean, callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by NotificationBadgeApi. */
    val codec: MessageCodec<Any?> by lazy {
      NotificationBadgeApiPigeonCodec()
    }
    /** Sets up an instance of `NotificationBadgeApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NotificationBadgeApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notification_badge.NotificationBadgeApi.isSupported$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isSupported{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NotificationBadgeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NotificationBadgeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notification_badge.NotificationBadgeApi.setCount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val countArg = args[0] as Long
            api.setCount(countArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NotificationBadgeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NotificationBadgeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notification_badge.NotificationBadgeApi.getBadgeCount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getBadgeCount{ result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NotificationBadgeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NotificationBadgeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notification_badge.NotificationBadgeApi.clearBadge$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.clearBadge{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NotificationBadgeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NotificationBadgeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notification_badge.NotificationBadgeApi.getDeviceManufacturer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getDeviceManufacturer{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NotificationBadgeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NotificationBadgeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notification_badge.NotificationBadgeApi.incrementCount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.incrementCount{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NotificationBadgeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NotificationBadgeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notification_badge.NotificationBadgeApi.decrementCount$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.decrementCount{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NotificationBadgeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NotificationBadgeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notification_badge.NotificationBadgeApi.checkPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.checkPermissions{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NotificationBadgeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NotificationBadgeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notification_badge.NotificationBadgeApi.requestPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestPermissions{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NotificationBadgeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NotificationBadgeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.notification_badge.NotificationBadgeApi.setAndroidNotificationConfig$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val notificationIconArg = args[0] as String
            val notificationTitleArg = args[1] as String?
            val notificationMessageArg = args[2] as String?
            val fallbackToUniversaLAndroidBadgerArg = args[3] as Boolean
            api.setAndroidNotificationConfig(notificationIconArg, notificationTitleArg, notificationMessageArg, fallbackToUniversaLAndroidBadgerArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NotificationBadgeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NotificationBadgeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
