// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class NotificationBadgeApiPigeonCodecReader: FlutterStandardReader {
}

private class NotificationBadgeApiPigeonCodecWriter: FlutterStandardWriter {
}

private class NotificationBadgeApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return NotificationBadgeApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return NotificationBadgeApiPigeonCodecWriter(data: data)
  }
}

class NotificationBadgeApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = NotificationBadgeApiPigeonCodec(readerWriter: NotificationBadgeApiPigeonCodecReaderWriter())
}


/// API for managing app icon badge counts on Android and iOS.
///
/// On iOS, badges are set directly via `UNUserNotificationCenter`.
/// On Android, manufacturer-specific providers are tried first; if none
/// succeed, a silent notification-based fallback is used (configurable via
/// [setAndroidNotificationConfig]).
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NotificationBadgeApi {
  /// Returns `true` if at least one badge provider is available on this device.
  func isSupported(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Sets the app icon badge to [count]. Returns `true` on success.
  func setCount(count: Int64, completion: @escaping (Result<Bool, Error>) -> Void)
  /// Returns the current badge count stored by the plugin.
  func getBadgeCount(completion: @escaping (Result<Int64, Error>) -> Void)
  /// Clears the badge by setting the count to 0. Returns `true` on success.
  func clearBadge(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Returns the device manufacturer string (e.g. `"samsung"`, `"Apple"`).
  func getDeviceManufacturer(completion: @escaping (Result<String, Error>) -> Void)
  /// Increments the badge count by 1. Returns `true` on success.
  func incrementCount(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Decrements the badge count by 1 (minimum 0). Returns `true` on success.
  func decrementCount(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Returns `true` if the app has permission to display badge notifications.
  func checkPermissions(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Requests permission to display badge notifications.
  ///
  /// Returns `true` if permission was granted. On Android below API 33,
  /// always returns `true`. On iOS, shows the system permission dialog.
  func requestPermissions(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Configures the notification used by the Android universal badge fallback.
  ///
  /// This is only relevant on Android. The universal fallback posts a silent,
  /// low-priority notification to display a badge count on devices where no
  /// manufacturer-specific badge API is available.
  ///
  /// - [notificationIcon]: drawable resource name in your app (default `ic_notification`).
  /// - [notificationTitle]: title shown in the notification shade. `null` renders a blank title.
  /// - [notificationMessage]: body text shown in the notification shade. `null` renders a blank body.
  /// - [fallbackToUniversaLAndroidBadger]: set to `false` to disable the fallback entirely.
  func setAndroidNotificationConfig(notificationIcon: String, notificationTitle: String?, notificationMessage: String?, fallbackToUniversaLAndroidBadger: Bool, completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NotificationBadgeApiSetup {
  static var codec: FlutterStandardMessageCodec { NotificationBadgeApiPigeonCodec.shared }
  /// Sets up an instance of `NotificationBadgeApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NotificationBadgeApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Returns `true` if at least one badge provider is available on this device.
    let isSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notification_badge.NotificationBadgeApi.isSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isSupportedChannel.setMessageHandler { _, reply in
        api.isSupported { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isSupportedChannel.setMessageHandler(nil)
    }
    /// Sets the app icon badge to [count]. Returns `true` on success.
    let setCountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notification_badge.NotificationBadgeApi.setCount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setCountChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let countArg = args[0] as! Int64
        api.setCount(count: countArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setCountChannel.setMessageHandler(nil)
    }
    /// Returns the current badge count stored by the plugin.
    let getBadgeCountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notification_badge.NotificationBadgeApi.getBadgeCount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBadgeCountChannel.setMessageHandler { _, reply in
        api.getBadgeCount { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getBadgeCountChannel.setMessageHandler(nil)
    }
    /// Clears the badge by setting the count to 0. Returns `true` on success.
    let clearBadgeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notification_badge.NotificationBadgeApi.clearBadge\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearBadgeChannel.setMessageHandler { _, reply in
        api.clearBadge { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      clearBadgeChannel.setMessageHandler(nil)
    }
    /// Returns the device manufacturer string (e.g. `"samsung"`, `"Apple"`).
    let getDeviceManufacturerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notification_badge.NotificationBadgeApi.getDeviceManufacturer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDeviceManufacturerChannel.setMessageHandler { _, reply in
        api.getDeviceManufacturer { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getDeviceManufacturerChannel.setMessageHandler(nil)
    }
    /// Increments the badge count by 1. Returns `true` on success.
    let incrementCountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notification_badge.NotificationBadgeApi.incrementCount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      incrementCountChannel.setMessageHandler { _, reply in
        api.incrementCount { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      incrementCountChannel.setMessageHandler(nil)
    }
    /// Decrements the badge count by 1 (minimum 0). Returns `true` on success.
    let decrementCountChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notification_badge.NotificationBadgeApi.decrementCount\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      decrementCountChannel.setMessageHandler { _, reply in
        api.decrementCount { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      decrementCountChannel.setMessageHandler(nil)
    }
    /// Returns `true` if the app has permission to display badge notifications.
    let checkPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notification_badge.NotificationBadgeApi.checkPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkPermissionsChannel.setMessageHandler { _, reply in
        api.checkPermissions { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      checkPermissionsChannel.setMessageHandler(nil)
    }
    /// Requests permission to display badge notifications.
    ///
    /// Returns `true` if permission was granted. On Android below API 33,
    /// always returns `true`. On iOS, shows the system permission dialog.
    let requestPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notification_badge.NotificationBadgeApi.requestPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionsChannel.setMessageHandler { _, reply in
        api.requestPermissions { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPermissionsChannel.setMessageHandler(nil)
    }
    /// Configures the notification used by the Android universal badge fallback.
    ///
    /// This is only relevant on Android. The universal fallback posts a silent,
    /// low-priority notification to display a badge count on devices where no
    /// manufacturer-specific badge API is available.
    ///
    /// - [notificationIcon]: drawable resource name in your app (default `ic_notification`).
    /// - [notificationTitle]: title shown in the notification shade. `null` renders a blank title.
    /// - [notificationMessage]: body text shown in the notification shade. `null` renders a blank body.
    /// - [fallbackToUniversaLAndroidBadger]: set to `false` to disable the fallback entirely.
    let setAndroidNotificationConfigChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.notification_badge.NotificationBadgeApi.setAndroidNotificationConfig\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setAndroidNotificationConfigChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let notificationIconArg = args[0] as! String
        let notificationTitleArg: String? = nilOrValue(args[1])
        let notificationMessageArg: String? = nilOrValue(args[2])
        let fallbackToUniversaLAndroidBadgerArg = args[3] as! Bool
        api.setAndroidNotificationConfig(notificationIcon: notificationIconArg, notificationTitle: notificationTitleArg, notificationMessage: notificationMessageArg, fallbackToUniversaLAndroidBadger: fallbackToUniversaLAndroidBadgerArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setAndroidNotificationConfigChannel.setMessageHandler(nil)
    }
  }
}
